/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dqdlphsonfqncbgvbjqw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxZGxwaHNvbmZxbmNiZ3ZianF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwMTgwMDUsImV4cCI6MjA3OTU5NDAwNX0.FZ4RJ5_I-AthHZJ4qgAB3YjYt05op-TkEFlFB6Xl8Ko"